.TH joinpdf 1 "November 2011"
.SH NAME
joinpdf \- a simple pdf concatenator.
.SH SYNOPSIS
.B joinpdf
.RI input.pdf
.RI [input2.pdf...]
.RI output.pdf
.SH DESCRIPTION
.\" Add any additional description here
.P
joinpdf is a tool that you can use if you have to deal with joining several pdf files. It will not join pdf files which have security enabled. This tool is requires a Java Runtime Environment (JRE).
.RE
.SH EXAMPLE
.P
joinpdf invoice.pdf order.pdf joined.png
.RE
.SH AUTHOR
joinpdf was originally written by Mark Thompson.
.P
This manual page was written by Romain Schmitz.
.SH "REPORTING BUGS"
Report joinpdf bugs to <https://github.com/slopjong/pdf-tools/issues/>.
