.TH splitpdf 1 "November 2011"
.SH NAME
splitpdf \- a simple page extractor
.SH SYNOPSIS
.B splitpdf
.RI input.pdf
.SH DESCRIPTION
.\" Add any additional description here
.P
splitpdf is a tool that you can use if you have to deal with extracting pages out of a pdf file. This tool is requires a Java Runtime Environment (JRE).
.RE
.SH EXAMPLE
.P
splitpdf book.pdf
.RE
.SH AUTHOR
splitpdf was originally written by Bruno Lowagie.
.P
This manual page was written by Romain Schmitz.
.SH "REPORTING BUGS"
Report splitpdf bugs to <https://github.com/slopjong/pdf-tools/issues/>.
