#!/bin/bash

case "$(uname)" in
	Linux)
		READLINK="readlink"
		;;
	Darwin)
		READLINK="greadlink"
		;;
	*)
		READLINK="readlink"
esac

MY_PATH=`${READLINK} -f $0`
MY_PATH=`dirname $MY_PATH`
LIB_PATH=${MY_PATH}/../lib

java -cp ${LIB_PATH}/itextpdf/itextpdf.jar:${LIB_PATH}/lightweight-pdf-tools.jar Split "$@"
